### ISSUE TITLE
champ autre

### ISSUE THREAD

**Issue by raphaelle-anfh** [seb-martin/anfh-ge-api-temp#20]
Il faudrait un champ libre "autre" pour permettre aux régions de renseigner les pré-requis, dates limites d'inscription...

**Comment by seb-martin** [comment]
OK pour un champs "Autre". Je le placerai, si ça convient, sous les champs "Contexte" et "Objectifs" de l'action.

A combien de caractères dois-je limiter le champs "Autre" ?

**Comment by seb-martin** [comment]
Oups, j'ai répondu un peu vite.

Pour moi, pas de soucis, je rajoute le champs et c'est parti. 

Mais ce n'est pas pareil pour GE qui, à ma connaissance, n'a pas prévu ce champs et qui ne pourra donc pas le fournir lorsque l'appli temporaire sera retirée.

Je me rapproche de HE pour avoir son avis.

**Comment by seb-martin** [comment]
Duplique #26
