### ISSUE TITLE
gestion des sessions

### ISSUE THREAD

**Issue by raphaelle-anfh** [seb-martin/anfh-ge-api-temp#21]
comment fait-on pour gérer les sessions au niveau des dates (2 jours + 1 jours) 
exemple : une formation de 3 jours (2 + 1)
du 11 au 12 février + 15 mars 2016

**Comment by seb-martin** [comment]
Oh là, ça sent l'usine à gaz !

On ne gère pas les sessions. Une session (dans le jargon de l'ANFH) est rattachée à un module.

Pour reprendre ton exemple, dans le système métier, la formation de 3 jours (2 + 1) est une formation comportant 2 modules, l'un de 2 jours, le second de 1 jour. Sont ensuite rattachées les sessions aux modules avec une session pour le premier module du 11 au 12 février et une session pour le second module la 15 mars.

On obtient ainsi un arbre Formation > Modules > Sessions.
- Formation
  - Module 1
    - Session 1 : du 11 au 12 février
  - Module 2
    - Session 1 : le 15 mars

ANFH.fr est là pour afficher des informations à titre indicatif, laissons le soin à GE de gérer ce genre de problématique métier.

Ceci dit, peut être que les termes "Du" "Au" sont confusant et qu'il vaudrait mieux utiliser les termes "Entre le" "Et le".

**Comment by raphaelle-anfh** [comment]
il faudrait pouvoir renseigner les dates par module ? 
ou ajouter un champ libre au niveau des dates pour pouvoir indiquer du 11 au 12 février + le 15 mars
regarde l'action : PIC/AFR15 Parcours Métier Animateur socioculturel - CREATIVITE DANS LES ATELIERS D’ACTIVITÉS PROPOSES AUX PERSONNES A CAPACITÉ RÉDUITE ET/OU VIEILLISSANTES ACCUEILLIES DANS LES ETABLISSEMENTS

je ne vois pas trop comment faire...

**Comment by seb-martin** [comment]
Pour accéder à cette demande, il faudrait
- Modifier la spécification et la faire repasser par un circuit de validation (COM + GE)
- Faire évoluer le schéma des données pour prendre en compte les modifications apportées à la spec
- Modifier les traitements, les interfaces applicative et utilisateur

Etant donné que la mise en production est attendue pour le 04/03/2016, le temps imparti pour accéder à cette demande n'est pas suffisant.

Pour reprendre l'exemple de l'action PIC/AFR15 :
- C'est une action possédant un module de 6 heures.
- C'est une action possédant 3 "groupes" dans le calendrier :
  - Entre le 25/02/2016 et le 10/03/2016 à AMIENS
  - Entre le 02/03/2016 et le 17/06/2016 à AMIENS
  - Entre le 15/09/2016 et le 30/09/2016

**Comment by seb-martin** [comment]
La mise en production a été repoussée à la date du 25/03/2014 pour permettre la réalisation de cette demande.

A faire :
- [x] #26 
- [x] #27
- [x] #28
- [x] #29
- [x] #43
