### ISSUE TITLE
champs contexte et objectif

### ISSUE THREAD

**Issue by raphaelle-anfh** [seb-martin/anfh-ge-api-temp#22]
Les 2 premiers champs contexte et objectif doivent être obligatoires.

**Comment by seb-martin** [comment]
Cela veut dire que les utilisateurs ne pourront enregistrer l'action que si il y a un contexte et des objectifs. 

Ces 2 champs réclamant une certaine rédaction, je crains que nos utilisateurs se contentent de mentions "plus tard" ou "à voir" pour pouvoir enregistrer leur travail sans être bloqués par ces champs.

Je pense qu'il vaudrait mieux **empêcher la publication si ces deux champs ne sont pas renseignés** : 
- Les utilisateurs pourront enregistrer leur travail sans contexte ou objectifs parasites
- Les utilisateurs ne pourront pas afficher sur ANFH.fr des actions sans contexte ou objectifs.

Quand dis-tu ?

**Comment by raphaelle-anfh** [comment]
Oui, parfait.
