### ISSUE TITLE
Manque des contenus entre l'ancien site et l'appli

### ISSUE THREAD

**Issue by raphaelle-anfh** [seb-martin/anfh-ge-api-temp#50]
Alpes
Aucun contenu 
(il y en a sur l’ancien site : http://v1.anfh.fr/site/anfhfr/offre-de-formation?type_etablissement=all&filiere=all&action_formation=all&region=685)

ALS
Aucun contenu
1 action sur ANFH.fr : http://v1.anfh.fr/site/anfhfr/offre-de-formation?type_etablissement=all&filiere=all&action_formation=all&region=22

AQU
6 actions sur le site (http://v1.anfh.fr/site/anfhfr/offre-de-formation?type_etablissement=all&filiere=all&action_formation=all&region=52) ,
4 dans l’appli

BAS
Aucun contenus
Pourtant présents sur ANFH.fr http://v1.anfh.fr/site/anfhfr/offre-de-formation?type_etablissement=all&filiere=all&action_formation=all&region=66

FRA
Manque du contenu : 
que 9 actions dans l’appli, 
bien plus sur le site : http://v1.anfh.fr/site/anfhfr/offre-de-formation?page=1&type_etablissement=all&filiere=all&action_formation=all&region=59

HAU
Manque du contenu
7 actions dans l’appli + sur anfh.fr http://v1.anfh.fr/site/anfhfr/offre-de-formation?page=4&type_etablissement=all&filiere=all&action_formation=all&region=67

DMA
Manque de contenu
http://v1.anfh.fr/site/anfhfr/offre-de-formation?type_etablissement=all&filiere=all&action_formation=all&region=75

Midi-pyrénées
Manque des contenus
http://v1.anfh.fr/site/anfhfr/offre-de-formation?type_etablissement=all&filiere=all&action_formation=all&region=75

Poitou
http://v1.anfh.fr/site/anfhfr/offre-de-formation?type_etablissement=all&filiere=all&action_formation=all&region=70
manque des contenus

**Comment by seb-martin** [comment]
Les offres manquantes sont les offres créées avant 2014 (j'avais demandé à Supersoniks un export des offres créées à partir du 01/01/2014).

Je m'aperçois cependant que certaines offres créées avant 2014 ont été reconduites jusqu'en 2015. Exemple : [AQU : GPE 4 - AFR / FORMATION DES TUTEURS ENCADRANT DES ETUDIANTS PARAMEDICAUX](http://v1.anfh.fr/actions-de-formation/gpe-4-afr-formation-des-tuteurs-encadrant-des-etudiants-paramedicaux)

Je viens de réclamer à Supersoniks un export complet [Ticket 8994](http://supersoniks.net/issues/8994)

**Comment by seb-martin** [comment]
L'export complet ne sera pas disponible avant le 29/03/2016, après la mise en production prévue le 25/03/2016 :disappointed:
1. Le déploiement de l'application reste prévu pour le 25/03/2016, avec la reprise de données actuelle
2. L'application ne sera utilisé que par la délégation PIC qui pourra ajouter/modifier/supprimer (les éventuelles modifications/suppression opérées par les autres délégations seront perdues !)
3. A la réception de l'export, une nouvelle reprise de données sera effectuée **en excluant la délégation PIC de cette reprise** pour conserver leur saisie

**Comment by seb-martin** [comment]
Le 31/03/2016, Supersoniks a livré un export des offres créées avant le 01/01/2014 ([Ticket 8994](http://supersoniks.net/issues/8994)).

Commit 7977093838be36f501de37abc33db79b360e49f8

**Comment by seb-martin** [comment]
Les offres datant d'avant 2015 sont à affecter sur 2015 et ne doivent pas être publiées

**Comment by seb-martin** [comment]
Test reprise, liste des régions/exercices avec des données :
- [x] ALP
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] ALS
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] AQU
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] AUV
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] BAS
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] BGN
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] BRE
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] CEN
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] CHA
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] COR
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] DGY
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] DMA
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] FRA
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] HAU
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] IDF
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] LAN
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] LIM
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] LOR
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] MID
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] NOR
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] PAY
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] PIC
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] POI
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] PRO
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] REU
  - [x] 2015
  - [x] 2016
  - [ ] 2017
- [x] RHO
  - [x] 2015
  - [x] 2016
  - [ ] 2017

**Comment by seb-martin** [comment]
Amélioration **uniquement sur 2016**
- [x] ALP : 
  - [x] Retire "ALPES :"
- [x] ALS : 
  - _Aucune amélioration_
- [x] AQU : 
  - [x] Retire "AQU / ", "AQU : ", "AQUITAINE", "Gpe 1, "Gpe 2", "AFR//"
- [x] AUV : 
  - [x] Retirer "AUV / "
- [x] BAS : 
  - _Aucune amélioration_
- [x] BGN : 
  - [x]Retire "BGN - ", "Bourgogne - "
- [x] BRE : 
  - _Aucune amélioration_
- [x] CEN : 
  - [x] Retirer "CENTRE : ", "Centre : "
- [x] CHA : 
  - [x] Retirer "ANFH CHA - ", "AR : ", "CHAMPAGNE-ARDENNE : "
  - [x] "AC 2016" -> Action coordonnée
- [x] COR : 
  - _Aucune amélioration_
- [x] DGY : 
  - _Aucune amélioration_
- [x] DMA : 
  - [x] Retirer "AFR à venir : ", "Martinique : "
- [x] FRA : 
  - [x] Retire "AR :", "F.COMTE", "F.Comté : ", "FR-COMTE / ", "FRA - ", FRA ", "FRANCHE-COMTE : ", "Franche-Comté "
- [x] HAU : 
  - [x] Retirer "2016. "
- [x] IDF : 
  - _Aucune amélioration_
- [x] LAN : 
  - _Aucune amélioration_
- [x] LIM : 
  - [x] Retirer "LIM / ", "LIM ", "LIM/", "LIMOUSIN / ", "LIMOUSIN : ", "LIMOUSIN "
- [x] LOR : 
  - [x] Retirer " - Région Lorraine"
- [x] MID : 
  - Retirer "MIDI PYRENEES - ", "MP - ", "MP / ", "Midi Pyrénées : "
  - "AFR _N_" -> Référence régionale
- [x] NOR : 
  - [x] Retirer "NORD : "
- [x] PAY : 
  - _Aucune amélioration_
- [x] PIC : 
  - Retirer "AFR / ", "PIC / ", "PIC/", "PICARDIE : ", "Picardie : "
  - "AC / " -> Action coordonnée
- [x] POI : 
  - _Aucune amélioration_
- [x] PRO : 
  - [x] Retirer "PACA / ", "PACA : "
- [x] REU : 
  - [x] Retirer "OCEAN INDIEN : ", "Ocean Indien: ", "Océan indien : "
- [x] RHO : 
  - [x] Retirer "AFR - ", "RHONE /", "RHONE : "
  - [x] "PIE" -> Action coordonnée
