### ISSUE TITLE
champ nature

### ISSUE THREAD

**Issue by raphaelle-anfh** [seb-martin/anfh-ge-api-temp#51]
on a le choix entre régionale ou nationale mais il faudrait pouvoir mettre :
AFR 
AFC
AFN

champ qui apparaît sous l'intitulé dans le filet
![image](https://cloud.githubusercontent.com/assets/17404945/13851501/c1c160c6-ec5e-11e5-9c89-b64ef5902656.png)

**Comment by seb-martin** [comment]
Jusqu'à présent, la spec prévoit pour la nature deux valeurs :
- `N` : Pour les actions nationales
- `R` : Pour les actions régionales

OK pour les coordonnées (vu avec @HE/SI et @KR/SI) : 
- `C` : Pour les actions coordonnées

**Comment by seb-martin** [comment]
La [spec](https://drive.google.com/open?id=1mGhBQKpE_jTKBTFomEtEWp3L7fZFS5dYFgcQWklF6lk) a été mise à jour en conséquence.
